apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-custom-policy-agent
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: custom-policy-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
