{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ipfs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml (.Values.persistence.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
{{- end }}