export interface DocumentStructure {
    documentOutline: DocumentOutline
    semanticConditions: SemanticCondition[]
    documentBlocks: DocumentBlock[]
    customMetaData: MetaData[]
    schemaRefs: SchemaReferenceSet
    policyRefs: PolicyReference[]
    validation: ValidationProfile
    templateType: TemplateTypeValue
    // TBD: title, description, jurisdiction, etc.
    // Other fields like type, version, etc will be generated by backend and stored in database, not editable by Template Creator
}

// ---- DocumentOutline ----

export type DocumentOutline = DocumentOutlineBlock[]

export interface DocumentOutlineBlock {
    blockId: string
    isRoot?: boolean
    children: string[]
}

// ---- SemanticCondition ----

export interface SemanticCondition {
    conditionId: string
    conditionName: string
    schemaVersion: 'v1'
    parameters: SemanticConditionParameter[]
}

export type SemanticParameterType = 'date' | 'string' | 'integer' | 'decimal'

export const SemanticOperate = {
    lessThan: 'lessThan',
    lessThanOrEqual: 'lessThanOrEqual',
    greaterThan: 'greaterThan',
    greaterThanOrEqual: 'greaterThanOrEqual',
    equal: 'equal',
    notEqual: 'notEqual',
} as const

export type SemanticOperateType = (typeof SemanticOperate)[keyof typeof SemanticOperate]

export interface SemanticParameterOperator {
    operate: SemanticOperateType
    /**
     * Target could be other parameters or basic value, 
     * for example: 
     * { "operate": "greaterThan", "value": "100" } 
     * { "operate": "greaterThan", "value": "{{startDate}}" } 
     */
    targets: string[]
}

export interface SemanticConditionParameter {
    parameterName: string
    type: SemanticParameterType
    schemaRef: string
    semanticPath: DomainSemanticPath
    isRequired: boolean
    operators: SemanticParameterOperator[]
    value: unknown
}

export const SEMANTIC_CONDITION_SCHEMA_VERSION = 'v1'

// ---- Validation Metadata ----

export const FACIS_SCHEMA_REFS = {
    documentStructure: 'facis.dcs.document-structure.v1',
    templateData: 'facis.dcs.template-data.v1',
    contractData: 'facis.dcs.contract-data.v1',
    semanticCondition: 'facis.dcs.semantic-condition.v1',
    party: 'facis.dcs.party.v1',
    contract: 'facis.dcs.contract.v1',
    service: 'facis.dcs.service.v1',
    signature: 'facis.dcs.signature.v1',
} as const

export const FACIS_DOMAIN_FIELDS = [
    { semanticPath: 'company.legalName', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company legal name' },
    { semanticPath: 'company.location.street', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company street' },
    { semanticPath: 'company.location.postalCode', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company postal code' },
    { semanticPath: 'company.location.city', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company city' },
    { semanticPath: 'company.location.country', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company country' },
    { semanticPath: 'contract.jurisdiction', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'string', label: 'Contract jurisdiction' },
    { semanticPath: 'contract.validity.startDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Validity start date' },
    { semanticPath: 'contract.validity.endDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Validity end date' },
    { semanticPath: 'service.sla.availability', schemaRef: FACIS_SCHEMA_REFS.service, type: 'decimal', label: 'SLA availability' },
    { semanticPath: 'service.sla.responseTime', schemaRef: FACIS_SCHEMA_REFS.service, type: 'integer', label: 'SLA response time' },
    { semanticPath: 'signature.requiredLevel', schemaRef: FACIS_SCHEMA_REFS.signature, type: 'string', label: 'Required signature level' },
] as const

export type DomainSemanticPath = (typeof FACIS_DOMAIN_FIELDS)[number]['semanticPath']

export const FACIS_BLOCK_CATALOGUE = [
    { blockCatalogueId: 'facis.block.document.section', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.section', label: 'Document section' },
    { blockCatalogueId: 'facis.block.text.free', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.freeText', label: 'Free text' },
    { blockCatalogueId: 'facis.block.clause.custom', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.clause', label: 'Custom clause' },
    { blockCatalogueId: 'facis.block.party.company', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company', label: 'Company party' },
    { blockCatalogueId: 'facis.block.party.company.location', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company.location', label: 'Company location' },
    { blockCatalogueId: 'facis.block.sla.availability', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.sla.availability', label: 'SLA availability' },
    { blockCatalogueId: 'facis.block.contract.validity', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.validity', label: 'Contract validity' },
    { blockCatalogueId: 'facis.block.signature.requirement', schemaRef: FACIS_SCHEMA_REFS.signature, semanticPath: 'signature.requiredLevel', label: 'Signature requirement' },
] as const

export interface SchemaReferenceSet {
    documentStructure: string
    semanticCondition: string
    templateData?: string
    contractData?: string
}

export interface PolicyReference {
    policyId: string
    version: string
    enforcementPoint: 'template:create' | 'template:update' | 'template:verify' | 'contract:create' | 'contract:update' | 'contract:submit'
}

export interface ValidationProfile {
    schemaVersion: 'v1'
    profile: 'FACIS_DCS_TEMPLATE_V1' | 'FACIS_DCS_CONTRACT_V1'
    requiredPolicies: string[]
}

export const FACIS_TEMPLATE_POLICY_REFS: PolicyReference[] = [
    { policyId: 'facis.dcs.template.structure', version: 'v1', enforcementPoint: 'template:create' },
    { policyId: 'facis.dcs.template.semantic-conditions', version: 'v1', enforcementPoint: 'template:verify' },
]

export const FACIS_CONTRACT_POLICY_REFS: PolicyReference[] = [
    { policyId: 'facis.dcs.contract.structure', version: 'v1', enforcementPoint: 'contract:create' },
    { policyId: 'facis.dcs.contract.semantic-values', version: 'v1', enforcementPoint: 'contract:update' },
]

export const FACIS_TEMPLATE_VALIDATION_PROFILE: ValidationProfile = {
    schemaVersion: 'v1',
    profile: 'FACIS_DCS_TEMPLATE_V1',
    requiredPolicies: FACIS_TEMPLATE_POLICY_REFS.map((policy) => policy.policyId),
}

export const FACIS_CONTRACT_VALIDATION_PROFILE: ValidationProfile = {
    schemaVersion: 'v1',
    profile: 'FACIS_DCS_CONTRACT_V1',
    requiredPolicies: FACIS_CONTRACT_POLICY_REFS.map((policy) => policy.policyId),
}

export const DocumentBlockType = {
    Section: 'SECTION',
    Text: 'TEXT',
    Clause: 'CLAUSE',
    ApprovedTemplate: 'APPROVED_TEMPLATE',
    MergedApprovedTemplate: 'MERGED_APPROVED_TEMPLATE',
} as const

// ---- DocumentBlock ----

export type DocumentBlockType = (typeof DocumentBlockType)[keyof typeof DocumentBlockType]

export type DocumentBlock = SectionBlock | TextBlock | ClauseBlock | ApprovedTemplateBlock | MergedApprovedTemplateBlock

interface BaseBlock {
    blockId: string
    type: DocumentBlockType
    blockCatalogueId?: string
    schemaRef?: string
    semanticPath?: string
    title?: string
    text: string
}

export interface SectionBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Section']
}

export interface TextBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Text']
}

export interface ClauseBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Clause']
    conditionIds: string[]
    // TBD: render
    // number: 0.##
    // date: yyyy-MM-dd
}

export interface ApprovedTemplateBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['ApprovedTemplate']
    templateId: string
    version: number
    document_number: string
}

export interface MergedApprovedTemplateBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['MergedApprovedTemplate']
    templateId: string
    version: number
    document_number: string
}

export function isSectionBlock(block: DocumentBlock): block is SectionBlock {
    return block.type === DocumentBlockType.Section
}

export function isTextBlock(block: DocumentBlock): block is TextBlock {
    return block.type === DocumentBlockType.Text
}

export function isClauseBlock(block: DocumentBlock): block is ClauseBlock {
    return block.type === DocumentBlockType.Clause
}

export function isApprovedTemplateBlock(block: DocumentBlock): block is ApprovedTemplateBlock {
    return block.type === DocumentBlockType.ApprovedTemplate
}

export function isMergedApprovedTemplateBlock(block: DocumentBlock): block is MergedApprovedTemplateBlock {
    return block.type === DocumentBlockType.MergedApprovedTemplate
}

// ---- MetaData ----

export interface MetaData {
    name: string
    value: string
}

// ---- TemplateTypeValue ----

export const TemplateType = {
    subContract: 'SUB_CONTRACT',
    frameContract: 'FRAME_CONTRACT',
} as const

export type TemplateTypeValue = (typeof TemplateType)[keyof typeof TemplateType]
