import type {
  DcsOperator,
  ParameterType,
  SemanticProfile,
  SemanticRule,
  SLAAgreement,
  TemplateVariable,
  PlaceholderBinding,
  PolicyBundle,
  UiMetadata,
} from '@/models/semantic/facis-dcs-semantic'

export interface DocumentStructure {
  '@context'?: string
  documentOutline: DocumentOutline
  semanticConditions: SemanticCondition[]
  documentBlocks: DocumentBlock[]
  customMetaData: MetaData[]
  schemaRefs: SchemaReferenceSet
  policyRefs: PolicyReference[]
  validation: ValidationProfile
  semanticProfile?: SemanticProfile
  templateVariables?: TemplateVariable[]
  placeholderBindings?: PlaceholderBinding[]
  semanticRules?: SemanticRule[]
  policyBundle?: PolicyBundle
  sla?: SLAAgreement
  templateType: TemplateTypeValue
  // TBD: title, description, jurisdiction, etc.
  // Other fields like type, version, etc will be generated by backend and stored in database, not editable by Template Creator
}

// ---- DocumentOutline ----

export type DocumentOutline = DocumentOutlineBlock[]

export interface DocumentOutlineBlock {
  blockId: string
  isRoot?: boolean
  children: string[]
}

// ---- SemanticCondition ----

export interface SemanticCondition {
  conditionId: string
  conditionName: string
  schemaVersion: 'v1'
  entityType?: SemanticEntityType
  entityRole?: SemanticEntityRole
  parameters: SemanticConditionParameter[]
}

export type SemanticParameterType = ParameterType
export type SemanticEntityType = string
export type SemanticEntityRole = string

export const SemanticOperate = {
  lessThan: 'LessThan',
  lessThanOrEqual: 'LessThanOrEqual',
  greaterThan: 'GreaterThan',
  greaterThanOrEqual: 'GreaterThanOrEqual',
  equal: 'Equals',
  notEqual: 'NotEquals',
  between: 'Between',
  contains: 'Contains',
  matchesRegex: 'MatchesRegex',
} as const

export type SemanticOperateType = DcsOperator

export interface SemanticParameterOperator {
  operate: SemanticOperateType
  /**
   * Target could be other parameters or basic value,
   * for example:
   * { "operate": "GreaterThan", "value": "100" }
   * { "operate": "GreaterThan", "value": "{{startDate}}" }
   */
  targets: unknown[]
}

export interface SemanticConditionParameter {
  parameterName: string
  type: SemanticParameterType
  schemaRef: string
  semanticPath: DomainSemanticPath
  valueConstraint?: SemanticValueConstraint
  defaultValue?: unknown
  semanticMeaning?: string
  uiMetadata?: UiMetadata
  isRequired: boolean
  operators: SemanticParameterOperator[]
  value: unknown
}

export const SEMANTIC_CONDITION_SCHEMA_VERSION = 'v1'

export interface SemanticValueConstraint {
  format?: 'iso-3166-1-alpha-3' | 'iso-4217' | 'eidas-signature-level' | 'controlled-vocabulary'
  pattern?: string
  allowedValues?: readonly string[]
  valueOptions?: readonly SemanticValueOption[]
  allowedValuesRef?: string
  min?: number
  max?: number
  description?: string
}

export interface SemanticValueOption {
  value: string
  label?: string
  symbol?: string
}

// ---- Validation Metadata ----

export const FACIS_SCHEMA_REFS = {
  documentStructure: 'facis.dcs.document-structure.v1',
  templateData: 'facis.dcs.template-data.v1',
  contractData: 'facis.dcs.contract-data.v1',
  semanticCondition: 'facis.dcs.semantic-condition.v1',
  party: 'facis.dcs.party.v1',
  contract: 'facis.dcs.contract.v1',
  service: 'facis.dcs.service.v1',
  signature: 'facis.dcs.signature.v1',
} as const

export type DomainSemanticPath = string

export interface DomainFieldDefinition {
  semanticPath: DomainSemanticPath
  schemaRef: string
  type: SemanticParameterType
  label: string
  group: string
  statementType?: string
  valueConstraint?: SemanticValueConstraint
}

export interface SchemaReferenceSet {
  documentStructure: string
  semanticCondition: string
  templateData?: string
  contractData?: string
  jsonLdContext?: string
  ontology?: string
  shaclShapes?: string
}

export interface PolicyReference {
  policyId: string
  version: string
  enforcementPoint:
    | 'template:create'
    | 'template:update'
    | 'template:verify'
    | 'contract:create'
    | 'contract:update'
    | 'contract:submit'
}

export interface ValidationProfile {
  schemaVersion: 'v1'
  profile: 'FACIS_DCS_TEMPLATE_V1' | 'FACIS_DCS_CONTRACT_V1'
  requiredPolicies: string[]
}

export const FACIS_TEMPLATE_POLICY_REFS: PolicyReference[] = [
  { policyId: 'facis.dcs.template.structure', version: 'v1', enforcementPoint: 'template:create' },
  { policyId: 'facis.dcs.template.semantic-conditions', version: 'v1', enforcementPoint: 'template:verify' },
]

export const FACIS_CONTRACT_POLICY_REFS: PolicyReference[] = [
  { policyId: 'facis.dcs.contract.structure', version: 'v1', enforcementPoint: 'contract:create' },
  { policyId: 'facis.dcs.contract.semantic-values', version: 'v1', enforcementPoint: 'contract:update' },
]

export const FACIS_TEMPLATE_VALIDATION_PROFILE: ValidationProfile = {
  schemaVersion: 'v1',
  profile: 'FACIS_DCS_TEMPLATE_V1',
  requiredPolicies: FACIS_TEMPLATE_POLICY_REFS.map((policy) => policy.policyId),
}

export const FACIS_CONTRACT_VALIDATION_PROFILE: ValidationProfile = {
  schemaVersion: 'v1',
  profile: 'FACIS_DCS_CONTRACT_V1',
  requiredPolicies: FACIS_CONTRACT_POLICY_REFS.map((policy) => policy.policyId),
}

export const DocumentBlockType = {
  Section: 'SECTION',
  Text: 'TEXT',
  Clause: 'CLAUSE',
  ApprovedTemplate: 'APPROVED_TEMPLATE',
  MergedApprovedTemplate: 'MERGED_APPROVED_TEMPLATE',
} as const

// ---- DocumentBlock ----

export type DocumentBlockType = (typeof DocumentBlockType)[keyof typeof DocumentBlockType]

export type DocumentBlock = SectionBlock | TextBlock | ClauseBlock | ApprovedTemplateBlock | MergedApprovedTemplateBlock

interface BaseBlock {
  blockId: string
  type: DocumentBlockType
  blockCatalogueId?: string
  schemaRef?: string
  semanticPath?: string
  title?: string
  text: string
}

export interface SectionBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Section']
}

export interface TextBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Text']
}

export interface ClauseBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Clause']
  conditionIds: string[]
  // TBD: render
  // number: 0.##
  // date: yyyy-MM-dd
}

export interface ApprovedTemplateBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['ApprovedTemplate']
  templateId: string
  version: number
  document_number: string
}

export interface MergedApprovedTemplateBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['MergedApprovedTemplate']
  templateId: string
  version: number
  document_number: string
}

export function isSectionBlock(block: DocumentBlock): block is SectionBlock {
  return block.type === DocumentBlockType.Section
}

export function isTextBlock(block: DocumentBlock): block is TextBlock {
  return block.type === DocumentBlockType.Text
}

export function isClauseBlock(block: DocumentBlock): block is ClauseBlock {
  return block.type === DocumentBlockType.Clause
}

export function isApprovedTemplateBlock(block: DocumentBlock): block is ApprovedTemplateBlock {
  return block.type === DocumentBlockType.ApprovedTemplate
}

export function isMergedApprovedTemplateBlock(block: DocumentBlock): block is MergedApprovedTemplateBlock {
  return block.type === DocumentBlockType.MergedApprovedTemplate
}

// ---- MetaData ----

export interface MetaData {
  name: string
  value: string
}

// ---- TemplateTypeValue ----

export const TemplateType = {
  subContract: 'SUB_CONTRACT',
  frameContract: 'FRAME_CONTRACT',
} as const

export type TemplateTypeValue = (typeof TemplateType)[keyof typeof TemplateType]
