export interface DocumentStructure {
    documentOutline: DocumentOutline
    semanticConditions: SemanticCondition[]
    documentBlocks: DocumentBlock[]
    customMetaData: MetaData[]
    schemaRefs: SchemaReferenceSet
    policyRefs: PolicyReference[]
    validation: ValidationProfile
    templateType: TemplateTypeValue
    // TBD: title, description, jurisdiction, etc.
    // Other fields like type, version, etc will be generated by backend and stored in database, not editable by Template Creator
}

// ---- DocumentOutline ----

export type DocumentOutline = DocumentOutlineBlock[]

export interface DocumentOutlineBlock {
    blockId: string
    isRoot?: boolean
    children: string[]
}

// ---- SemanticCondition ----

export interface SemanticCondition {
    conditionId: string
    conditionName: string
    schemaVersion: 'v1'
    parameters: SemanticConditionParameter[]
}

export type SemanticParameterType = 'date' | 'string' | 'integer' | 'decimal'

export const SemanticOperate = {
    lessThan: 'lessThan',
    lessThanOrEqual: 'lessThanOrEqual',
    greaterThan: 'greaterThan',
    greaterThanOrEqual: 'greaterThanOrEqual',
    equal: 'equal',
    notEqual: 'notEqual',
} as const

export type SemanticOperateType = (typeof SemanticOperate)[keyof typeof SemanticOperate]

export interface SemanticParameterOperator {
    operate: SemanticOperateType
    /**
     * Target could be other parameters or basic value, 
     * for example: 
     * { "operate": "greaterThan", "value": "100" } 
     * { "operate": "greaterThan", "value": "{{startDate}}" } 
     */
    targets: string[]
}

export interface SemanticConditionParameter {
    parameterName: string
    type: SemanticParameterType
    schemaRef: string
    semanticPath: DomainSemanticPath
    valueConstraint?: SemanticValueConstraint
    isRequired: boolean
    operators: SemanticParameterOperator[]
    value: unknown
}

export const SEMANTIC_CONDITION_SCHEMA_VERSION = 'v1'

export interface SemanticValueConstraint {
    format?: 'iso-3166-1-alpha-3' | 'iso-4217' | 'eidas-signature-level' | 'controlled-vocabulary'
    pattern?: string
    allowedValues?: readonly string[]
    allowedValuesRef?: string
    min?: number
    max?: number
    description?: string
}

// ---- Validation Metadata ----

export const FACIS_SCHEMA_REFS = {
    documentStructure: 'facis.dcs.document-structure.v1',
    templateData: 'facis.dcs.template-data.v1',
    contractData: 'facis.dcs.contract-data.v1',
    semanticCondition: 'facis.dcs.semantic-condition.v1',
    party: 'facis.dcs.party.v1',
    contract: 'facis.dcs.contract.v1',
    service: 'facis.dcs.service.v1',
    signature: 'facis.dcs.signature.v1',
} as const

const FACIS_DOMAIN_FIELD_DEFINITIONS = [
    { semanticPath: 'company.legalName', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company legal name', group: 'Parties' },
    { semanticPath: 'company.registrationNumber', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company registration number', group: 'Parties' },
    { semanticPath: 'company.vatId', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company VAT ID', group: 'Parties' },
    { semanticPath: 'company.representative.name', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Representative name', group: 'Parties' },
    { semanticPath: 'company.representative.role', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Representative role', group: 'Parties' },
    { semanticPath: 'company.contact.email', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company contact email', group: 'Parties' },
    { semanticPath: 'company.contact.phone', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company contact phone', group: 'Parties' },
    { semanticPath: 'company.location.street', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company street', group: 'Address' },
    { semanticPath: 'company.location.postalCode', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company postal code', group: 'Address' },
    { semanticPath: 'company.location.city', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company city', group: 'Address' },
    { semanticPath: 'company.location.region', schemaRef: FACIS_SCHEMA_REFS.party, type: 'string', label: 'Company region/state', group: 'Address' },
    {
        semanticPath: 'company.location.country',
        schemaRef: FACIS_SCHEMA_REFS.party,
        type: 'string',
        label: 'Company country',
        group: 'Address',
        valueConstraint: {
            format: 'iso-3166-1-alpha-3',
            pattern: '^[A-Z]{3}$',
            allowedValuesRef: 'ISO 3166-1 alpha-3',
            allowedValues: ['DEU', 'AUT', 'CHE', 'FRA', 'NLD', 'BEL', 'LUX', 'POL', 'CZE', 'ESP', 'ITA', 'GBR', 'USA'],
            description: 'Use ISO 3166-1 alpha-3 country codes, for example DEU instead of Germany.',
        },
    },
    { semanticPath: 'contract.title', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'string', label: 'Contract title', group: 'Contract basics' },
    {
        semanticPath: 'contract.type',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Contract type',
        group: 'Contract basics',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['frameworkAgreement', 'serviceAgreement', 'dataProcessingAgreement', 'nda', 'leaseAgreement', 'purchaseAgreement'],
            description: 'Use the FACIS contract type vocabulary.',
        },
    },
    {
        semanticPath: 'contract.jurisdiction',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Contract jurisdiction',
        group: 'Legal',
        valueConstraint: {
            format: 'iso-3166-1-alpha-3',
            pattern: '^[A-Z]{3}$',
            allowedValuesRef: 'ISO 3166-1 alpha-3',
            allowedValues: ['DEU', 'AUT', 'CHE', 'FRA', 'NLD', 'BEL', 'LUX', 'POL', 'CZE', 'ESP', 'ITA', 'GBR', 'USA'],
            description: 'Use ISO 3166-1 alpha-3 jurisdiction codes.',
        },
    },
    {
        semanticPath: 'contract.governingLaw',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Governing law',
        group: 'Legal',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['DE', 'AT', 'CH', 'FR', 'NL', 'BE', 'EU'],
            description: 'Use the agreed governing-law code vocabulary.',
        },
    },
    { semanticPath: 'contract.disputeResolution.venue', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'string', label: 'Dispute venue', group: 'Legal' },
    {
        semanticPath: 'contract.disputeResolution.method',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Dispute method',
        group: 'Legal',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['court', 'arbitration', 'mediation'],
            description: 'Use the FACIS dispute resolution vocabulary.',
        },
    },
    { semanticPath: 'contract.validity.startDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Validity start date', group: 'Dates' },
    { semanticPath: 'contract.validity.endDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Validity end date', group: 'Dates' },
    { semanticPath: 'contract.effectiveDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Effective date', group: 'Dates' },
    { semanticPath: 'contract.renewal.noticePeriodDays', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'integer', label: 'Renewal notice period', group: 'Dates' },
    { semanticPath: 'contract.termination.noticePeriodDays', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'integer', label: 'Termination notice period', group: 'Dates' },
    { semanticPath: 'contract.payment.amount', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'decimal', label: 'Payment amount', group: 'Commercial' },
    {
        semanticPath: 'contract.payment.currency',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Payment currency',
        group: 'Commercial',
        valueConstraint: {
            format: 'iso-4217',
            pattern: '^[A-Z]{3}$',
            allowedValuesRef: 'ISO 4217',
            allowedValues: ['EUR', 'USD', 'GBP', 'CHF', 'PLN', 'CZK'],
            description: 'Use ISO 4217 currency codes.',
        },
    },
    { semanticPath: 'contract.payment.dueDate', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'date', label: 'Payment due date', group: 'Commercial' },
    { semanticPath: 'contract.payment.dueDays', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'integer', label: 'Payment due days', group: 'Commercial' },
    { semanticPath: 'contract.liability.capAmount', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'decimal', label: 'Liability cap amount', group: 'Risk' },
    { semanticPath: 'contract.liability.currency', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'string', label: 'Liability currency', group: 'Risk' },
    { semanticPath: 'contract.insurance.minimumCoverage', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'decimal', label: 'Minimum insurance coverage', group: 'Risk' },
    { semanticPath: 'contract.confidentiality.durationMonths', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'integer', label: 'Confidentiality duration', group: 'Legal' },
    {
        semanticPath: 'contract.dataProtection.role',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Data protection role',
        group: 'Compliance',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['controller', 'processor', 'jointController', 'subProcessor'],
            description: 'Use the GDPR role vocabulary.',
        },
    },
    {
        semanticPath: 'contract.auditRights.frequency',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'Audit rights frequency',
        group: 'Compliance',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['onDemand', 'annual', 'semiAnnual', 'quarterly'],
            description: 'Use the FACIS audit frequency vocabulary.',
        },
    },
    {
        semanticPath: 'contract.ipRights.ownership',
        schemaRef: FACIS_SCHEMA_REFS.contract,
        type: 'string',
        label: 'IP rights ownership',
        group: 'Legal',
        valueConstraint: {
            format: 'controlled-vocabulary',
            allowedValues: ['customer', 'supplier', 'joint', 'preExistingRetained'],
            description: 'Use the FACIS IP ownership vocabulary.',
        },
    },
    { semanticPath: 'contract.forceMajeure.noticeDays', schemaRef: FACIS_SCHEMA_REFS.contract, type: 'integer', label: 'Force majeure notice days', group: 'Risk' },
    { semanticPath: 'service.description', schemaRef: FACIS_SCHEMA_REFS.service, type: 'string', label: 'Service description', group: 'Service' },
    { semanticPath: 'service.scope', schemaRef: FACIS_SCHEMA_REFS.service, type: 'string', label: 'Service scope', group: 'Service' },
    { semanticPath: 'service.deliverable.name', schemaRef: FACIS_SCHEMA_REFS.service, type: 'string', label: 'Deliverable name', group: 'Service' },
    { semanticPath: 'service.deliverable.acceptanceCriteria', schemaRef: FACIS_SCHEMA_REFS.service, type: 'string', label: 'Acceptance criteria', group: 'Service' },
    {
        semanticPath: 'service.sla.availability',
        schemaRef: FACIS_SCHEMA_REFS.service,
        type: 'decimal',
        label: 'SLA availability',
        group: 'SLA',
        valueConstraint: {
            min: 0,
            max: 100,
            description: 'Availability percentage from 0 to 100.',
        },
    },
    { semanticPath: 'service.sla.responseTime', schemaRef: FACIS_SCHEMA_REFS.service, type: 'integer', label: 'SLA response time', group: 'SLA' },
    { semanticPath: 'service.sla.resolutionTime', schemaRef: FACIS_SCHEMA_REFS.service, type: 'integer', label: 'SLA resolution time', group: 'SLA' },
    { semanticPath: 'service.sla.supportHours', schemaRef: FACIS_SCHEMA_REFS.service, type: 'string', label: 'Support hours', group: 'SLA' },
    {
        semanticPath: 'signature.requiredLevel',
        schemaRef: FACIS_SCHEMA_REFS.signature,
        type: 'string',
        label: 'Required signature level',
        group: 'Signature',
        valueConstraint: {
            format: 'eidas-signature-level',
            allowedValues: ['SES', 'AES', 'QES'],
            description: 'Use eIDAS signature level codes.',
        },
    },
    { semanticPath: 'signature.requiredSignerRole', schemaRef: FACIS_SCHEMA_REFS.signature, type: 'string', label: 'Required signer role', group: 'Signature' },
    { semanticPath: 'signature.deadline', schemaRef: FACIS_SCHEMA_REFS.signature, type: 'date', label: 'Signature deadline', group: 'Signature' },
] as const

export type DomainSemanticPath = (typeof FACIS_DOMAIN_FIELD_DEFINITIONS)[number]['semanticPath']

export interface DomainFieldDefinition {
    semanticPath: DomainSemanticPath
    schemaRef: string
    type: SemanticParameterType
    label: string
    group: string
    valueConstraint?: SemanticValueConstraint
}

export const FACIS_DOMAIN_FIELDS: readonly DomainFieldDefinition[] = FACIS_DOMAIN_FIELD_DEFINITIONS

export const FACIS_BLOCK_CATALOGUE = [
    { blockCatalogueId: 'facis.block.document.section', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.section', label: 'Document section', group: 'Basic' },
    { blockCatalogueId: 'facis.block.text.free', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.freeText', label: 'Free text', group: 'Basic' },
    { blockCatalogueId: 'facis.block.clause.custom', schemaRef: FACIS_SCHEMA_REFS.documentStructure, semanticPath: 'document.clause', label: 'Custom clause', group: 'Basic' },
    { blockCatalogueId: 'facis.block.party.company', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company', label: 'Company party', group: 'Parties' },
    { blockCatalogueId: 'facis.block.party.company.location', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company.location', label: 'Company location', group: 'Parties' },
    { blockCatalogueId: 'facis.block.party.representative', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company.representative', label: 'Company representative', group: 'Parties' },
    { blockCatalogueId: 'facis.block.party.contact', schemaRef: FACIS_SCHEMA_REFS.party, semanticPath: 'company.contact', label: 'Company contact', group: 'Parties' },
    { blockCatalogueId: 'facis.block.contract.basics', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract', label: 'Contract basics', group: 'Contract' },
    { blockCatalogueId: 'facis.block.contract.validity', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.validity', label: 'Contract validity', group: 'Contract' },
    { blockCatalogueId: 'facis.block.contract.jurisdiction', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.jurisdiction', label: 'Jurisdiction', group: 'Contract' },
    { blockCatalogueId: 'facis.block.contract.renewal', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.renewal', label: 'Renewal terms', group: 'Contract' },
    { blockCatalogueId: 'facis.block.contract.termination', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.termination', label: 'Termination terms', group: 'Contract' },
    { blockCatalogueId: 'facis.block.contract.payment', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.payment', label: 'Payment terms', group: 'Commercial' },
    { blockCatalogueId: 'facis.block.contract.liability', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.liability', label: 'Liability', group: 'Risk' },
    { blockCatalogueId: 'facis.block.contract.insurance', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.insurance', label: 'Insurance', group: 'Risk' },
    { blockCatalogueId: 'facis.block.contract.confidentiality', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.confidentiality', label: 'Confidentiality', group: 'Legal' },
    { blockCatalogueId: 'facis.block.contract.data-protection', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.dataProtection', label: 'Data protection', group: 'Compliance' },
    { blockCatalogueId: 'facis.block.contract.audit-rights', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.auditRights', label: 'Audit rights', group: 'Compliance' },
    { blockCatalogueId: 'facis.block.contract.ip-rights', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.ipRights', label: 'IP rights', group: 'Legal' },
    { blockCatalogueId: 'facis.block.contract.force-majeure', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.forceMajeure', label: 'Force majeure', group: 'Risk' },
    { blockCatalogueId: 'facis.block.contract.dispute-resolution', schemaRef: FACIS_SCHEMA_REFS.contract, semanticPath: 'contract.disputeResolution', label: 'Dispute resolution', group: 'Legal' },
    { blockCatalogueId: 'facis.block.service.description', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.description', label: 'Service description', group: 'Service' },
    { blockCatalogueId: 'facis.block.service.scope', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.scope', label: 'Service scope', group: 'Service' },
    { blockCatalogueId: 'facis.block.service.deliverable', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.deliverable', label: 'Deliverable', group: 'Service' },
    { blockCatalogueId: 'facis.block.sla.availability', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.sla.availability', label: 'SLA availability', group: 'SLA' },
    { blockCatalogueId: 'facis.block.sla.response-time', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.sla.responseTime', label: 'SLA response time', group: 'SLA' },
    { blockCatalogueId: 'facis.block.sla.resolution-time', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.sla.resolutionTime', label: 'SLA resolution time', group: 'SLA' },
    { blockCatalogueId: 'facis.block.sla.support', schemaRef: FACIS_SCHEMA_REFS.service, semanticPath: 'service.sla.supportHours', label: 'Support hours', group: 'SLA' },
    { blockCatalogueId: 'facis.block.signature.requirement', schemaRef: FACIS_SCHEMA_REFS.signature, semanticPath: 'signature.requiredLevel', label: 'Signature requirement', group: 'Signature' },
    { blockCatalogueId: 'facis.block.signature.signer-role', schemaRef: FACIS_SCHEMA_REFS.signature, semanticPath: 'signature.requiredSignerRole', label: 'Signer role', group: 'Signature' },
    { blockCatalogueId: 'facis.block.signature.deadline', schemaRef: FACIS_SCHEMA_REFS.signature, semanticPath: 'signature.deadline', label: 'Signature deadline', group: 'Signature' },
] as const

export interface SchemaReferenceSet {
    documentStructure: string
    semanticCondition: string
    templateData?: string
    contractData?: string
}

export interface PolicyReference {
    policyId: string
    version: string
    enforcementPoint: 'template:create' | 'template:update' | 'template:verify' | 'contract:create' | 'contract:update' | 'contract:submit'
}

export interface ValidationProfile {
    schemaVersion: 'v1'
    profile: 'FACIS_DCS_TEMPLATE_V1' | 'FACIS_DCS_CONTRACT_V1'
    requiredPolicies: string[]
}

export const FACIS_TEMPLATE_POLICY_REFS: PolicyReference[] = [
    { policyId: 'facis.dcs.template.structure', version: 'v1', enforcementPoint: 'template:create' },
    { policyId: 'facis.dcs.template.semantic-conditions', version: 'v1', enforcementPoint: 'template:verify' },
]

export const FACIS_CONTRACT_POLICY_REFS: PolicyReference[] = [
    { policyId: 'facis.dcs.contract.structure', version: 'v1', enforcementPoint: 'contract:create' },
    { policyId: 'facis.dcs.contract.semantic-values', version: 'v1', enforcementPoint: 'contract:update' },
]

export const FACIS_TEMPLATE_VALIDATION_PROFILE: ValidationProfile = {
    schemaVersion: 'v1',
    profile: 'FACIS_DCS_TEMPLATE_V1',
    requiredPolicies: FACIS_TEMPLATE_POLICY_REFS.map((policy) => policy.policyId),
}

export const FACIS_CONTRACT_VALIDATION_PROFILE: ValidationProfile = {
    schemaVersion: 'v1',
    profile: 'FACIS_DCS_CONTRACT_V1',
    requiredPolicies: FACIS_CONTRACT_POLICY_REFS.map((policy) => policy.policyId),
}

export const DocumentBlockType = {
    Section: 'SECTION',
    Text: 'TEXT',
    Clause: 'CLAUSE',
    ApprovedTemplate: 'APPROVED_TEMPLATE',
    MergedApprovedTemplate: 'MERGED_APPROVED_TEMPLATE',
} as const

// ---- DocumentBlock ----

export type DocumentBlockType = (typeof DocumentBlockType)[keyof typeof DocumentBlockType]

export type DocumentBlock = SectionBlock | TextBlock | ClauseBlock | ApprovedTemplateBlock | MergedApprovedTemplateBlock

interface BaseBlock {
    blockId: string
    type: DocumentBlockType
    blockCatalogueId?: string
    schemaRef?: string
    semanticPath?: string
    title?: string
    text: string
}

export interface SectionBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Section']
}

export interface TextBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Text']
}

export interface ClauseBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['Clause']
    conditionIds: string[]
    // TBD: render
    // number: 0.##
    // date: yyyy-MM-dd
}

export interface ApprovedTemplateBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['ApprovedTemplate']
    templateId: string
    version: number
    document_number: string
}

export interface MergedApprovedTemplateBlock extends BaseBlock {
    type: (typeof DocumentBlockType)['MergedApprovedTemplate']
    templateId: string
    version: number
    document_number: string
}

export function isSectionBlock(block: DocumentBlock): block is SectionBlock {
    return block.type === DocumentBlockType.Section
}

export function isTextBlock(block: DocumentBlock): block is TextBlock {
    return block.type === DocumentBlockType.Text
}

export function isClauseBlock(block: DocumentBlock): block is ClauseBlock {
    return block.type === DocumentBlockType.Clause
}

export function isApprovedTemplateBlock(block: DocumentBlock): block is ApprovedTemplateBlock {
    return block.type === DocumentBlockType.ApprovedTemplate
}

export function isMergedApprovedTemplateBlock(block: DocumentBlock): block is MergedApprovedTemplateBlock {
    return block.type === DocumentBlockType.MergedApprovedTemplate
}

// ---- MetaData ----

export interface MetaData {
    name: string
    value: string
}

// ---- TemplateTypeValue ----

export const TemplateType = {
    subContract: 'SUB_CONTRACT',
    frameContract: 'FRAME_CONTRACT',
} as const

export type TemplateTypeValue = (typeof TemplateType)[keyof typeof TemplateType]
