export interface DocumentStructure {
  documentOutline: DocumentOutline
  semanticConditions: SemanticCondition[]
  documentBlocks: DocumentBlock[]
  customMetaData: MetaData[]
  templateType: TemplateTypeValue
  // TBD: title, description, jurisdiction, etc.
  // Other fields like type, version, etc will be generated by backend and stored in database, not editable by Template Creator
}

// ---- DocumentOutline ----

export type DocumentOutline = DocumentOutlineBlock[]

export interface DocumentOutlineBlock {
  blockId: string
  isRoot?: boolean
  children: string[]
}

// ---- SemanticCondition ----

export interface SemanticCondition {
  conditionId: string
  conditionName: string
  schemaVersion: 'v1'
  parameters: SemanticConditionParameter[]
}

export type SemanticParameterType = 'date' | 'string' | 'integer' | 'decimal'

export const SemanticOperate = {
  lessThan: 'lessThan',
  lessThanOrEqual: 'lessThanOrEqual',
  greaterThan: 'greaterThan',
  greaterThanOrEqual: 'greaterThanOrEqual',
  equal: 'equal',
  notEqual: 'notEqual',
} as const

export type SemanticOperateType = (typeof SemanticOperate)[keyof typeof SemanticOperate]

export interface SemanticParameterOperator {
  operate: SemanticOperateType
  /**
   * Target could be other parameters or basic value,
   * for example:
   * { "operate": "greaterThan", "value": "100" }
   * { "operate": "greaterThan", "value": "{{startDate}}" }
   */
  targets: string[]
}

export interface SemanticConditionParameter {
  parameterName: string
  type: SemanticParameterType
  isRequired: boolean
  operators: SemanticParameterOperator[]
  value: unknown
}

export const SEMANTIC_CONDITION_SCHEMA_VERSION = 'v1'

export const DocumentBlockType = {
  Section: 'SECTION',
  Text: 'TEXT',
  Clause: 'CLAUSE',
  ApprovedTemplate: 'APPROVED_TEMPLATE',
  MergedApprovedTemplate: 'MERGED_APPROVED_TEMPLATE',
} as const

// ---- DocumentBlock ----

export type DocumentBlockType = (typeof DocumentBlockType)[keyof typeof DocumentBlockType]

export type DocumentBlock = SectionBlock | TextBlock | ClauseBlock | ApprovedTemplateBlock | MergedApprovedTemplateBlock

interface BaseBlock {
  blockId: string
  type: DocumentBlockType
  title?: string
  text: string
}

export interface SectionBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Section']
}

export interface TextBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Text']
}

export interface ClauseBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['Clause']
  conditionIds: string[]
  // TBD: render
  // number: 0.##
  // date: yyyy-MM-dd
}

export interface ApprovedTemplateBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['ApprovedTemplate']
  templateId: string
  version: number
  document_number: string
}

export interface MergedApprovedTemplateBlock extends BaseBlock {
  type: (typeof DocumentBlockType)['MergedApprovedTemplate']
  templateId: string
  version: number
  document_number: string
}

export function isSectionBlock(block: DocumentBlock): block is SectionBlock {
  return block.type === DocumentBlockType.Section
}

export function isTextBlock(block: DocumentBlock): block is TextBlock {
  return block.type === DocumentBlockType.Text
}

export function isClauseBlock(block: DocumentBlock): block is ClauseBlock {
  return block.type === DocumentBlockType.Clause
}

export function isApprovedTemplateBlock(block: DocumentBlock): block is ApprovedTemplateBlock {
  return block.type === DocumentBlockType.ApprovedTemplate
}

export function isMergedApprovedTemplateBlock(block: DocumentBlock): block is MergedApprovedTemplateBlock {
  return block.type === DocumentBlockType.MergedApprovedTemplate
}

// ---- MetaData ----

export interface MetaData {
  name: string
  value: string
}

// ---- TemplateTypeValue ----

export const TemplateType = {
  subContract: 'SUB_CONTRACT',
  frameContract: 'FRAME_CONTRACT',
} as const

export type TemplateTypeValue = (typeof TemplateType)[keyof typeof TemplateType]