apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ipfs-document-manager
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: ipfs-document-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
