apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digital-contracting-service.fullname" . }}
  labels:
    {{- include "digital-contracting-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "digital-contracting-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "digital-contracting-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "digital-contracting-service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OIDC_ISSUER_URL
              {{- if .Values.oidc.issuerURLSecretRef.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.issuerURLSecretRef.name | quote }}
                  key: {{ .Values.oidc.issuerURLSecretRef.key | quote }}
              {{- else }}
              value: {{ include "digital-contracting-service.oidcIssuerURL" . | quote }}
              {{- end }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientID | quote }}
            - name: OIDC_REDIRECT_URI
              value: {{ .Values.oidc.redirectURI | quote }}
            - name: OIDC_LOGOUT_REDIRECT_URI
              value: {{ .Values.oidc.logoutRedirectURI | quote }}
            - name: DATABASE_URL
              {{- if .Values.database.secretRef.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretRef.name | quote }}
                  key: {{ .Values.database.secretRef.key | quote }}
              {{- else }}
              value: {{ include "digital-contracting-service.databaseURL" . | quote }}
              {{- end }}
            - name: NATS_URL
              {{- if .Values.messaging.secretRef.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messaging.secretRef.name | quote }}
                  key: {{ .Values.messaging.secretRef.key | quote }}
              {{- else }}
              value: {{ include "digital-contracting-service.natsURL" . | quote }}
              {{- end }}
            - name: FEDERATED_CATALOGUE_API_URL
              {{- if and .Values.federatedCatalogue.secretRef .Values.federatedCatalogue.secretRef.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.federatedCatalogue.secretRef.name | quote }}
                  key: {{ .Values.federatedCatalogue.secretRef.key | quote }}
              {{- else }}
              value: {{ .Values.federatedCatalogue.apiURL | quote }}
              {{- end }}
            - name: DCS_API_PATH
              value: {{ include "digital-contracting-service.apiPath" . | quote }}
            - name: DCS_UI_PATH
              value: {{ include "digital-contracting-service.uiPath" . | quote }}
            - name: IPFS_TENANT_BASE_URL
              value: {{ include "digital-contracting-service.ipfsTenantBaseURL" . | quote }}
            - name: IPFS_MFS_BASE_URL
              value: {{ include "digital-contracting-service.ipfsMfsBaseURL" . | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.customCA.enabled .Values.volumeMounts }}
          volumeMounts:
          {{- if .Values.customCA.enabled }}
            - name: custom-ca-certs
              mountPath: /usr/local/share/ca-certificates/custom
              readOnly: true
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.customCA.enabled .Values.volumes }}
      volumes:
      {{- if .Values.customCA.enabled }}
        - name: custom-ca-certs
          configMap:
            name: {{ .Values.customCA.configMapName }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
