{{- if and .Values.oid4vp.trust.enabled (not .Values.vault.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digital-contracting-service.oid4vpTrustConfigMapName" . }}
  labels:
    {{- include "digital-contracting-service.labels" . | nindent 4 }}
data:
  trust.json: |
{{ .Files.Get "files/oid4vp/trust.dev.json" | indent 4 }}
{{- end }}
