{{- if .Values.vault.enabled }}
{{- $vaultToken := dig "server" "dev" "devRootToken" "root" .Values.vault }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace "vault" }}
{{- if $existing }}
  {{- $vaultToken = index $existing.data "token" | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    {{- include "digital-contracting-service.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ $vaultToken | b64enc }}
{{- end }}
