replicaCount: 1

image:
  repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack/ipfs-document-manager
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  nodePort: null

ingress:
  enabled: false
  className: ""
  annotations: {}
  pathType: ImplementationSpecific
  hosts: []
  tls: []

ipfs:
  host: ""
  apiGatewayURL: ""
  rpcApiPort: 5001
  logLevel: "info"

config:
  serverMode: "production"
  listenPort: 8080

cors:
  active: true
  origins: "*"
  methods: "GET,POST,DELETE"

resources: {}

extraEnv: []
