apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statuslist-service
  labels:
    app.kubernetes.io/name: statuslist-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: statuslist-service
    app.kubernetes.io/instance: {{ .Release.Name }}
