image:
  repository: mongo
  tag: "7-jammy"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017
  nodePort: null

persistence:
  enabled: false
  size: 2Gi
  accessModes:
    - ReadWriteOnce

auth:
  username: "policy"
  password: "policy"

resources: {}
