package auth

import (
	"context"
	"database/sql"
	"errors"
	"log"
	"time"

	"github.com/jmoiron/sqlx"
	goa "goa.design/goa/v3/pkg"
	"goa.design/goa/v3/security"

	"digital-contracting-service/internal/auth/db"
	"digital-contracting-service/internal/base/conf"
	"digital-contracting-service/internal/middleware"
)

// JWTAuthenticator implements the Auther interface generated by Goa for the
// "jwt" security scheme. Embed this struct in every service implementation so
// that the service satisfies the generated Auther interface.
//
// Usage:
//
//	type myService struct {
//	    auth.JWTAuthenticator
//	}
type JWTAuthenticator struct {
	Validator    *middleware.OIDCValidator
	DB           *sqlx.DB
	AAttemptRepo db.AccessAttemptRepo
	LockRepo     db.IPLockoutRepo
}

// NewJWTAuthenticator returns a JWTAuthenticator backed by the given OIDC
// validator.
func NewJWTAuthenticator(v *middleware.OIDCValidator, db *sqlx.DB, aAttemptRepo db.AccessAttemptRepo, lockRepo db.IPLockoutRepo) JWTAuthenticator {
	return JWTAuthenticator{Validator: v, DB: db, AAttemptRepo: aAttemptRepo, LockRepo: lockRepo}
}

// JWTAuth validates a JWT token via the OIDC provider and checks that the
// caller possesses at least one of the required scopes (Keycloak realm roles).
// It returns an enriched context with the caller's roles on success.
func (a JWTAuthenticator) JWTAuth(ctx context.Context, token string, scheme *security.JWTScheme) (context.Context, error) {
	ip := middleware.IPFromContext(ctx)

	if token == "" {
		a.logAttempt(ctx, ip, nil, false)
		return ctx, goa.PermanentError("unauthorized", "missing JWT token")
	}

	info, err := a.Validator.ValidateToken(ctx, token)
	if err != nil {
		a.logAttempt(ctx, ip, nil, false)
		if err := a.checkAndLock(ctx, ip); err != nil {
			return ctx, err
		}
		return ctx, goa.PermanentError("unauthorized", "invalid token: %s", err)
	}

	if len(scheme.RequiredScopes) > 0 {
		if !hasAnyRole(info.Roles, scheme.RequiredScopes) {
			a.logAttempt(ctx, ip, &info.DID, false)
			if err := a.checkAndLock(ctx, ip); err != nil {
				return ctx, err
			}
			return ctx, goa.PermanentError("forbidden", "insufficient permissions: requires one of %v", scheme.RequiredScopes)
		}
	}

	a.logAttempt(ctx, ip, &info.DID, true)
	a.clearLock(ctx, ip)

	ctx = middleware.InjectAuthContext(ctx, info.Roles, info.DID, info.DID, info.ParticipantID)
	return ctx, nil
}

// hasAnyRole returns true if roles contains at least one of the required roles.
func hasAnyRole(roles []string, required []string) bool {
	set := make(map[string]struct{}, len(roles))
	for _, r := range roles {
		set[r] = struct{}{}
	}
	for _, r := range required {
		if _, ok := set[r]; ok {
			return true
		}
	}
	return false
}

// logAttempt writes a login attempt – errors are ignored so that a DB issue
// does not block the login flow.
func (a JWTAuthenticator) logAttempt(ctx context.Context, ip string, attemptBy *string, success bool) {

	tx, err := a.DB.BeginTxx(ctx, nil)
	if err != nil {
		return
	}
	defer func(tx *sqlx.Tx) {
		if err := tx.Rollback(); err != nil && !errors.Is(err, sql.ErrTxDone) {
			log.Printf("could not rollback transaction: %v", err)
		}
	}(tx)

	_ = a.AAttemptRepo.Create(ctx, tx, db.AccessAttempt{
		IPAddress:   ip,
		AttemptBy:   attemptBy,
		AttemptedAt: time.Now(),
		Success:     success,
		Service:     ctx.Value(goa.ServiceKey).(string),
		Method:      ctx.Value(goa.MethodKey).(string),
	})

	_ = tx.Commit()
}

func (a JWTAuthenticator) checkAndLock(ctx context.Context, ip string) error {
	tx, err := a.DB.BeginTxx(ctx, nil)
	if err != nil {
		return nil
	}
	defer func(tx *sqlx.Tx) {
		if err := tx.Rollback(); err != nil && !errors.Is(err, sql.ErrTxDone) {
			log.Printf("could not rollback transaction: %v", err)
		}
	}(tx)

	count, err := a.AAttemptRepo.CountFailedAttemptsByIP(ctx, tx, ip, time.Now().Add(-conf.LoginLockoutDuration()))

	if err == nil && count >= conf.LoginAttemptsThresholdInDuration() {
		lockUntil := time.Now().Add(conf.LoginLockoutDuration())
		_ = a.LockRepo.SetLockout(ctx, tx, ip, lockUntil)
		_ = tx.Commit()
		return goa.PermanentError("unauthorized", "too many failed attempts, locked until %s", lockUntil.Format(time.RFC3339))
	}

	_ = tx.Commit()
	return nil
}

func (a JWTAuthenticator) clearLock(ctx context.Context, ip string) {
	tx, err := a.DB.BeginTxx(ctx, nil)
	if err != nil {
		return
	}
	defer func(tx *sqlx.Tx) {
		if err := tx.Rollback(); err != nil && !errors.Is(err, sql.ErrTxDone) {
			log.Printf("could not rollback transaction: %v", err)
		}
	}(tx)

	_ = a.LockRepo.ClearLockout(ctx, tx, ip)
	_ = tx.Commit()
}
