// Package verify implements MR/HR content hash consistency checking (DCS-FR-CWE-04, DCS-FR-CWE-05).
//
// A PDF generated by the builder package always contains the source JSON-LD as an EmbeddedFile
// attachment named "contract.jsonld". The verifier extracts that attachment, re-renders the base PDF
// from it, and compares SHA-256 hashes to confirm the human-readable view was not tampered with.
package verify

import (
	"bytes"
	"crypto/sha256"
	"crypto/x509"
	"digital-contracting-service/internal/pdfgeneration/c2pa"
	"encoding/hex"
	"fmt"
	"time"
)

// Result is returned by VerifyContract and VerifyTemplate.
type Result struct {
	// Match is true when the stored PDF was generated from the embedded JSON-LD
	// without alteration.
	Match bool `json:"match"`
	// JSONLDHash is the SHA-256 of the extracted JSON-LD bytes (hex).
	JSONLDHash string `json:"jsonld_hash"`
	// BasePDFHash is the SHA-256 of the re-generated base PDF (hex) derived from
	// the same JSON-LD (hex).
	BasePDFHash string `json:"base_pdf_hash"`
	// StoredBasePDFHash is the SHA-256 of the base layer of the stored PDF (before
	// any C2PA incremental updates).
	StoredBasePDFHash string `json:"stored_base_pdf_hash"`
	// ManifestSource indicates where C2PA provenance was verified from.
	// "embedded" — manifest present in the supplied PDF bytes.
	// "remote"   — manifest absent; canonical PDF fetched via FetchFn (DCS-OR-C2PA-008).
	// "none"     — no manifest found and FetchFn unavailable or returned no data.
	ManifestSource string `json:"manifest_source"`
	// C2PAManifestFound is true when a C2PA JUMBF manifest was detected in the PDF (DCS-OR-C2PA-006).
	C2PAManifestFound bool `json:"c2pa_manifest_found"`
	// C2PASignatureValid is true when the COSE_Sign1 signature in the manifest is
	// cryptographically valid (DCS-OR-C2PA-006).
	C2PASignatureValid bool `json:"c2pa_signature_valid"`
	// TSATimestampValid is true when the RFC 3161 sigTst token in the manifest was
	// parsed, verified, and the message imprint matched (DCS-OR-C2PA-009).
	TSATimestampValid bool `json:"tsa_timestamp_valid"`
	// TrustedTime is the genTime from the verified RFC 3161 token (DCS-OR-C2PA-009).
	// Zero value when TSATimestampValid is false.
	TrustedTime time.Time `json:"trusted_time,omitempty"`
	// VCProofValid is true when the embedded W3C VC Ed25519Signature2020 proof is
	// cryptographically valid (DCS-OR-C2PA-006).
	VCProofValid bool `json:"vc_proof_valid"`
	// StatusListURI is the URI of the status list service queried for revocation check.
	StatusListURI string `json:"status_list_uri,omitempty"`
	// LifecycleStatus is the contract state recorded in the latest C2PA lifecycle
	// assertion (draft, active, amended, suspended, terminated, expired, replaced).
	// This is the value the SRS requires shown as a verification banner (DCS-OR-C2PA-006).
	LifecycleStatus string `json:"lifecycle_status,omitempty"`
	// StatusListStatus is the live revocation state queried from the XFSC status list
	// service at the URI embedded in the VC's credentialStatus field (DCS-OR-C2PA-006).
	// "active" or "revoked"; empty when no status list URI was found or CheckStatusFn is nil.
	StatusListStatus string `json:"status_list_status,omitempty"`
	// PDFSignatureCount is the number of detached PDF signatures found via
	// /ByteRange entries.
	PDFSignatureCount int `json:"pdf_signature_count,omitempty"`
	// PDFSignatureValid is true when all detected PDF signatures verify
	// cryptographically as PKCS#7 detached signatures.
	PDFSignatureValid bool `json:"pdf_signature_valid"`
}

// ContractVerifier holds the dependencies needed to re-render a contract PDF.
type ContractVerifier struct {
	// BuildFn re-renders a PDF from the given JSON-LD bytes.
	// Injected so tests can provide a stub.
	BuildFn func(jsonld []byte) ([]byte, error)

	// FetchFn, when set, is called to retrieve the canonical full PDF (with C2PA
	// incremental updates attached) when the input PDF has no incremental updates.
	// This implements the DCS-OR-C2PA-008 remote manifest fallback: the verifier
	// fetches from IPFS if the embedded manifest has been stripped.
	FetchFn func() ([]byte, error)

	// FetchManifestFn, when set, retrieves the standalone remote C2PA manifest
	// bytes (JUMBF). This is the primary remote-manifest retrieval path required
	// by DCS-OR-C2PA-008.
	FetchManifestFn func() ([]byte, error)

	// CheckStatusFn, when set, is called with the statusListCredential URL and
	// statusListIndex parsed from the embedded VC to query live revocation state
	// (DCS-OR-C2PA-006). Returns "active" or "revoked".
	CheckStatusFn func(statusListCredential string, index uint32) (string, error)

	// TrustedSignerRoots, when non-nil, is the set of trusted root CAs for COSE
	// signer certificate chain validation (DCS-OR-C2PA-006). nil = skip (dev only).
	TrustedSignerRoots *x509.CertPool

	// TrustedTSARoots, when non-nil, is the set of trusted root CAs for the RFC 3161
	// TSA certificate chain (DCS-OR-C2PA-009). nil = skip (dev only).
	TrustedTSARoots *x509.CertPool

	// VCProofVerifier, when non-nil, performs actual cryptographic verification of
	// the W3C VC proof (DCS-OR-C2PA-006). Use c2pa.NewEd25519VCProofVerifier for
	// production deployments. When nil, falls back to a structural format check
	// (dev mode only — does not verify the signature).
	VCProofVerifier func(vcBytes []byte) (bool, error)
}

// TemplateVerifier holds the dependencies for template re-rendering.
type TemplateVerifier struct {
	BuildFn func(jsonld []byte) ([]byte, error)
	// FetchFn mirrors ContractVerifier.FetchFn for templates (DCS-OR-C2PA-008).
	FetchFn func() ([]byte, error)
	// FetchManifestFn mirrors ContractVerifier.FetchManifestFn for templates.
	FetchManifestFn func() ([]byte, error)
	// CheckStatusFn mirrors ContractVerifier.CheckStatusFn for templates (DCS-OR-C2PA-006).
	CheckStatusFn func(statusListCredential string, index uint32) (string, error)
	// TrustedSignerRoots mirrors ContractVerifier.TrustedSignerRoots for templates.
	TrustedSignerRoots *x509.CertPool
	// TrustedTSARoots mirrors ContractVerifier.TrustedTSARoots for templates.
	TrustedTSARoots *x509.CertPool
	// VCProofVerifier mirrors ContractVerifier.VCProofVerifier for templates.
	VCProofVerifier func(vcBytes []byte) (bool, error)
}

// Verify extracts the embedded JSON-LD from pdfBytes, re-renders the base PDF,
// and compares SHA-256 hashes. Also verifies C2PA signatures and extracts the status list URI from the VC.
func (v *ContractVerifier) Verify(pdfBytes []byte) (*Result, error) {
	opts := c2pa.VerifyOptions{
		TrustedSignerRoots: v.TrustedSignerRoots,
		TrustedTSARoots:    v.TrustedTSARoots,
	}
	return verify(pdfBytes, v.BuildFn, v.FetchFn, v.FetchManifestFn, v.CheckStatusFn, v.VCProofVerifier, opts)
}

// Verify is the template counterpart.
func (v *TemplateVerifier) Verify(pdfBytes []byte) (*Result, error) {
	opts := c2pa.VerifyOptions{
		TrustedSignerRoots: v.TrustedSignerRoots,
		TrustedTSARoots:    v.TrustedTSARoots,
	}
	return verify(pdfBytes, v.BuildFn, v.FetchFn, v.FetchManifestFn, v.CheckStatusFn, v.VCProofVerifier, opts)
}

func verify(
	pdfBytes []byte,
	buildFn func([]byte) ([]byte, error),
	fetchFn func() ([]byte, error),
	fetchManifestFn func() ([]byte, error),
	checkStatusFn func(statusListCredential string, index uint32) (string, error),
	vcProofVerifier func(vcBytes []byte) (bool, error),
	opts c2pa.VerifyOptions,
) (*Result, error) {
	manifestSource := "embedded"
	remoteManifestBytes := []byte(nil)

	// Check whether any incremental updates (C2PA manifests, PAdES signatures, etc.)
	// have been appended.  We look for a "startxref" keyword after the first %%EOF,
	// because every well-formed incremental update section ends with
	// "startxref\nN\n%%EOF" — whereas compressed stream bytes that accidentally
	// contain the %%EOF byte sequence will not have "startxref" immediately after.
	// When no incremental updates are found the manifest may have been stripped;
	// attempt to retrieve the canonical copy from remote storage (DCS-OR-C2PA-008).
	verifyPDFBytes := pdfBytes
	if !hasIncrementalUpdates(verifyPDFBytes) {
		if fetchManifestFn != nil {
			if manifestBytes, manifestErr := fetchManifestFn(); manifestErr == nil && len(manifestBytes) > 0 {
				remoteManifestBytes = manifestBytes
				manifestSource = "remote"
			}
		}
		if fetchFn != nil {
			canonical, fetchErr := fetchFn()
			if fetchErr == nil && hasIncrementalUpdates(canonical) {
				verifyPDFBytes = canonical
				manifestSource = "remote"
			} else {
				if len(remoteManifestBytes) == 0 {
					manifestSource = "none"
				}
			}
		} else {
			if len(remoteManifestBytes) == 0 {
				manifestSource = "none"
			}
		}
	}

	// Extract and verify C2PA manifest (DCS-OR-C2PA-006, DCS-OR-C2PA-009).
	// c2paManifestFound is set whenever manifest bytes are extracted, regardless of
	// signature validity, so callers can distinguish "manifest present but untrusted"
	// from "no manifest" (the distinction matters for banner rendering per DCS-OR-C2PA-006).
	c2paManifestFound, c2paSignatureValid := false, false
	tsaTimestampValid := false
	var trustedTime time.Time
	lifecycleStatus := ""
	mvr, manifestBytes, manifestErr := c2pa.ExtractAndVerifyManifestFull(verifyPDFBytes, opts)
	if len(manifestBytes) > 0 {
		c2paManifestFound = true
	}
	if manifestErr == nil && len(manifestBytes) > 0 {
		c2paSignatureValid = mvr.SignatureValid
		tsaTimestampValid = mvr.Timestamp.Valid
		if mvr.Timestamp.Valid {
			trustedTime = mvr.Timestamp.TrustedTime
		}
		lifecycleStatus = c2pa.ExtractLifecycleStatus(manifestBytes)
	}
	if !c2paManifestFound && len(remoteManifestBytes) > 0 {
		c2paManifestFound = true
		if rmvr, err := c2pa.VerifyManifestBytesFull(remoteManifestBytes, opts); err == nil {
			c2paSignatureValid = rmvr.SignatureValid
			if !tsaTimestampValid && rmvr.Timestamp.Valid {
				tsaTimestampValid = true
				trustedTime = rmvr.Timestamp.TrustedTime
			}
			lifecycleStatus = c2pa.ExtractLifecycleStatus(remoteManifestBytes)
		}
	}

	// Extract and verify W3C VC proof (DCS-OR-C2PA-006).
	// When vcProofVerifier is set, it performs actual cryptographic verification.
	// When nil (dev mode), fall back to the structural proof check.
	vcProofValid := false
	if _, vcBytes, err := c2pa.ExtractVC(verifyPDFBytes); err == nil && len(vcBytes) > 0 {
		if vcProofVerifier != nil {
			vcProofValid, _ = vcProofVerifier(vcBytes)
		} else {
			vcProofValid, _ = c2pa.VerifyVCProofStructural(vcBytes)
		}
	}

	// Verify detached PDF signatures (PAdES/PKCS#7) when present.
	pdfSigCount, pdfSigValid := 0, false
	if count, valid, sigErr := VerifyPDFSignatures(verifyPDFBytes, opts.TrustedSignerRoots); sigErr == nil {
		pdfSigCount = count
		pdfSigValid = valid
	}

	// Strip any incremental updates (C2PA manifests, future PAdES) appended after
	// the first %%EOF to recover the base PDF layer.
	basePDF, err := extractBasePDF(verifyPDFBytes)
	if err != nil {
		return nil, fmt.Errorf("extract base PDF layer: %w", err)
	}

	// Extract the embedded JSON-LD attachment from the base layer.
	jsonld, err := ExtractJSONLD(basePDF)
	if err != nil {
		return nil, fmt.Errorf("extract embedded JSON-LD: %w", err)
	}

	// Re-generate the base PDF from the JSON-LD.
	regenerated, err := buildFn(jsonld)
	if err != nil {
		return nil, fmt.Errorf("re-generate PDF: %w", err)
	}

	jsonldHash := sha256hex(jsonld)
	basePDFHash := sha256hex(regenerated)
	storedHash := sha256hex(basePDF)

	// Extract the status list URI and query live revocation state (DCS-OR-C2PA-006).
	statusListURI := ""
	statusListStatus := ""
	if vcProofValid {
		// Extract VC fields from the same byte source used for provenance checks.
		if _, vcBytes, vcErr := c2pa.ExtractVC(verifyPDFBytes); vcErr == nil && len(vcBytes) > 0 {
			statusListURI = c2pa.ExtractStatusListURI(vcBytes)
			if checkStatusFn != nil {
				if cred, idx, ok := c2pa.ExtractCredentialStatusFields(vcBytes); ok {
					var statusErr error
					statusListStatus, statusErr = checkStatusFn(cred, idx)
					if statusErr != nil {
						return nil, fmt.Errorf("query status list (DCS-OR-C2PA-006): %w", statusErr)
					}
				}
			}
		}
	}

	return &Result{
		Match:              bytes.Equal(basePDF, regenerated),
		JSONLDHash:         jsonldHash,
		BasePDFHash:        basePDFHash,
		StoredBasePDFHash:  storedHash,
		ManifestSource:     manifestSource,
		C2PAManifestFound:  c2paManifestFound,
		C2PASignatureValid: c2paSignatureValid,
		TSATimestampValid:  tsaTimestampValid,
		TrustedTime:        trustedTime,
		VCProofValid:       vcProofValid,
		StatusListURI:      statusListURI,
		LifecycleStatus:    lifecycleStatus,
		StatusListStatus:   statusListStatus,
		PDFSignatureCount:  pdfSigCount,
		PDFSignatureValid:  pdfSigValid,
	}, nil
}

// extractBasePDF returns the bytes up to and including the first %%EOF marker,
// discarding any incremental updates appended afterwards (C2PA, PAdES).
func extractBasePDF(pdf []byte) ([]byte, error) {
	eofMarker := []byte("%%EOF")
	idx := bytes.Index(pdf, eofMarker)
	if idx == -1 {
		return nil, fmt.Errorf("%%EOF marker not found in PDF")
	}
	end := idx + len(eofMarker)
	// Advance past any trailing newline so the hash is stable.
	for end < len(pdf) && (pdf[end] == '\n' || pdf[end] == '\r') {
		end++
	}
	return pdf[:end], nil
}

// ExtractJSONLD finds the EmbeddedFile stream named "contract.jsonld" in a PDF
// and returns its raw (uncompressed) content.
//
// fpdf compresses embedded files with zlib deflate and stores them as
// /EmbeddedFile stream objects. We locate the attachment by searching for the
// "contract.jsonld" filename in the PDF's embedded-files name tree and then
// decode the associated stream.
//
// This parser covers the attachment layout produced by the builder package.
func ExtractJSONLD(pdfBytes []byte) ([]byte, error) {
	// fpdf writes the attachment content as a compressed stream object.
	// The filename "contract.jsonld" appears in an /EmbeddedFiles name tree.
	// We locate the stream by searching for the EmbeddedFile type marker near
	// the filename reference.
	//
	// Strategy: find "contract.jsonld" in the raw bytes, then find the nearest
	// preceding compressed stream and decompress it.
	needle := []byte("contract.jsonld")
	pos := bytes.Index(pdfBytes, needle)
	if pos == -1 {
		return nil, fmt.Errorf("attachment \"contract.jsonld\" not found in PDF")
	}

	// Walk backwards to find the EmbeddedFile stream object.
	// fpdf serialises: "N 0 obj\n<< /Type /EmbeddedFile ... >>\nstream\n...bytes...\nendstream"
	// The stream content is zlib-compressed; fpdf uses Go's compress/zlib via its
	// internal xmem.compress helper.
	streamStart := bytes.LastIndex(pdfBytes[:pos], []byte("\nstream\n"))
	if streamStart == -1 {
		streamStart = bytes.LastIndex(pdfBytes[:pos], []byte("\nstream\r\n"))
	}
	if streamStart == -1 {
		return nil, fmt.Errorf("could not locate stream before attachment filename")
	}

	// Find the stream delimiter and endstream.
	afterStream := streamStart + len("\nstream\n")
	endStream := bytes.Index(pdfBytes[afterStream:], []byte("\nendstream"))
	if endStream == -1 {
		return nil, fmt.Errorf("endstream not found after attachment stream")
	}

	compressed := pdfBytes[afterStream : afterStream+endStream]
	decompressed, err := zlibDecompress(compressed)
	if err != nil {
		return nil, fmt.Errorf("decompress attachment stream: %w", err)
	}
	return decompressed, nil
}

// hasIncrementalUpdates returns true when pdfBytes contains at least one real
// PDF incremental update section appended after the first %%EOF.
//
// Detection: scan for "startxref" anywhere after the first %%EOF marker.
// Every incremental update must contain a new cross-reference section that
// ends with "startxref\nN\n%%EOF", so its presence is a reliable indicator.
// Compressed stream bytes that happen to contain the %%EOF sequence will not
// be followed by "startxref", making this test more robust than a simple
// byte-length comparison.
func hasIncrementalUpdates(pdf []byte) bool {
	eofMarker := []byte("%%EOF")
	idx := bytes.Index(pdf, eofMarker)
	if idx == -1 {
		return false
	}
	after := pdf[idx+len(eofMarker):]
	return bytes.Contains(after, []byte("startxref"))
}

func sha256hex(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}
