// Package verify implements MR/HR content hash consistency checking (DCS-FR-CWE-04, DCS-FR-CWE-05).
//
// A PDF generated by the builder package always contains the source JSON-LD as an EmbeddedFile
// attachment named "contract.jsonld". The verifier extracts that attachment, re-renders the base PDF
// from it, and compares SHA-256 hashes to confirm the human-readable view was not tampered with.
package verify

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

// Result is returned by VerifyContract and VerifyTemplate.
type Result struct {
	// Match is true when the stored PDF was generated from the embedded JSON-LD
	// without alteration.
	Match bool `json:"match"`
	// JSONLDHash is the SHA-256 of the extracted JSON-LD bytes (hex).
	JSONLDHash string `json:"jsonld_hash"`
	// BasePDFHash is the SHA-256 of the re-generated base PDF (hex) derived from
	// the same JSON-LD (hex).
	BasePDFHash string `json:"base_pdf_hash"`
	// StoredBasePDFHash is the SHA-256 of the base layer of the stored PDF (before
	// any C2PA incremental updates).
	StoredBasePDFHash string `json:"stored_base_pdf_hash"`
}

// ContractVerifier holds the dependencies needed to re-render a contract PDF.
type ContractVerifier struct {
	// BuildFn re-renders a PDF from the given JSON-LD bytes.
	// Injected so tests can provide a stub.
	BuildFn func(jsonld []byte) ([]byte, error)
}

// TemplateVerifier holds the dependencies for template re-rendering.
type TemplateVerifier struct {
	BuildFn func(jsonld []byte) ([]byte, error)
}

// Verify extracts the embedded JSON-LD from pdfBytes, re-renders the base PDF,
// and compares SHA-256 hashes.
func (v *ContractVerifier) Verify(pdfBytes []byte) (*Result, error) {
	return verify(pdfBytes, v.BuildFn)
}

// Verify is the template counterpart.
func (v *TemplateVerifier) Verify(pdfBytes []byte) (*Result, error) {
	return verify(pdfBytes, v.BuildFn)
}

func verify(pdfBytes []byte, buildFn func([]byte) ([]byte, error)) (*Result, error) {
	// Strip any incremental updates (C2PA manifests, future PAdES) appended after
	// the first %%EOF to recover the base PDF layer.
	basePDF, err := extractBasePDF(pdfBytes)
	if err != nil {
		return nil, fmt.Errorf("extract base PDF layer: %w", err)
	}

	// Extract the embedded JSON-LD attachment from the base layer.
	jsonld, err := ExtractJSONLD(basePDF)
	if err != nil {
		return nil, fmt.Errorf("extract embedded JSON-LD: %w", err)
	}

	// Re-generate the base PDF from the JSON-LD.
	regenerated, err := buildFn(jsonld)
	if err != nil {
		return nil, fmt.Errorf("re-generate PDF: %w", err)
	}

	jsonldHash := sha256hex(jsonld)
	basePDFHash := sha256hex(regenerated)
	storedHash := sha256hex(basePDF)

	return &Result{
		Match:             bytes.Equal(basePDF, regenerated),
		JSONLDHash:        jsonldHash,
		BasePDFHash:       basePDFHash,
		StoredBasePDFHash: storedHash,
	}, nil
}

// extractBasePDF returns the bytes up to and including the first %%EOF marker,
// discarding any incremental updates appended afterwards (C2PA, PAdES).
func extractBasePDF(pdf []byte) ([]byte, error) {
	eofMarker := []byte("%%EOF")
	idx := bytes.Index(pdf, eofMarker)
	if idx == -1 {
		return nil, fmt.Errorf("%%EOF marker not found in PDF")
	}
	end := idx + len(eofMarker)
	// Advance past any trailing newline so the hash is stable.
	for end < len(pdf) && (pdf[end] == '\n' || pdf[end] == '\r') {
		end++
	}
	return pdf[:end], nil
}

// ExtractJSONLD finds the EmbeddedFile stream named "contract.jsonld" in a PDF
// and returns its raw (uncompressed) content.
//
// fpdf compresses embedded files with zlib deflate and stores them as
// /EmbeddedFile stream objects. We locate the attachment by searching for the
// "contract.jsonld" filename in the PDF's embedded-files name tree and then
// decode the associated stream.
//
// This is a best-effort parser sufficient for our use case; it does not attempt
// full PDF spec compliance.
func ExtractJSONLD(pdfBytes []byte) ([]byte, error) {
	// fpdf writes the attachment content as a compressed stream object.
	// The filename "contract.jsonld" appears in an /EmbeddedFiles name tree.
	// We locate the stream by searching for the EmbeddedFile type marker near
	// the filename reference.
	//
	// Strategy: find "contract.jsonld" in the raw bytes, then find the nearest
	// preceding compressed stream and decompress it.
	needle := []byte("contract.jsonld")
	pos := bytes.Index(pdfBytes, needle)
	if pos == -1 {
		return nil, fmt.Errorf("attachment \"contract.jsonld\" not found in PDF")
	}

	// Walk backwards to find the EmbeddedFile stream object.
	// fpdf serialises: "N 0 obj\n<< /Type /EmbeddedFile ... >>\nstream\n...bytes...\nendstream"
	// The stream content is zlib-compressed; fpdf uses Go's compress/zlib via its
	// internal xmem.compress helper.
	streamStart := bytes.LastIndex(pdfBytes[:pos], []byte("\nstream\n"))
	if streamStart == -1 {
		streamStart = bytes.LastIndex(pdfBytes[:pos], []byte("\nstream\r\n"))
	}
	if streamStart == -1 {
		return nil, fmt.Errorf("could not locate stream before attachment filename")
	}

	// Find the stream delimiter and endstream.
	afterStream := streamStart + len("\nstream\n")
	endStream := bytes.Index(pdfBytes[afterStream:], []byte("\nendstream"))
	if endStream == -1 {
		return nil, fmt.Errorf("endstream not found after attachment stream")
	}

	compressed := pdfBytes[afterStream : afterStream+endStream]
	decompressed, err := zlibDecompress(compressed)
	if err != nil {
		return nil, fmt.Errorf("decompress attachment stream: %w", err)
	}
	return decompressed, nil
}

func sha256hex(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}
