package compiler

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"strings"
	"testing"
)

// findICCStreamInPDF extracts the raw ICC profile stream bytes from the PDF
// generated by renderPDF. The ICC profile is always written as object iccID (7).
func findICCStreamInPDF(pdf []byte) []byte {
	const objID = 7
	marker := []byte(fmt.Sprintf("%d 0 obj\n", objID))
	pos := bytes.Index(pdf, marker)
	if pos < 0 {
		return nil
	}
	streamTag := []byte("stream\n")
	streamPos := bytes.Index(pdf[pos:], streamTag)
	if streamPos < 0 {
		return nil
	}
	start := pos + streamPos + len(streamTag)
	end := bytes.Index(pdf[start:], []byte("\nendstream"))
	if end < 0 {
		return nil
	}
	return pdf[start : start+end]
}

// TestGeneratedPDFICCProfileIsStructurallyValid verifies that the ICC profile
// embedded in every generated PDF has a valid ICC header. Adobe Acrobat and
// other strict viewers reject PDFs whose /DestOutputProfile stream does not
// begin with a properly structured ICC profile (minimum 128-byte header,
// 'acsp' signature at bytes 36-39, and a size field that matches the stream
// length).
func TestGeneratedPDFICCProfileIsStructurallyValid(t *testing.T) {
	doc := documentModel{
		Title:         "icc-test",
		EmbeddedPayload: []byte(`{}`),
		PayloadHash:   strings.Repeat("0", 64),
		FileID:        strings.Repeat("0", 64),
		NamespaceMap:  map[string]string{},
	}

	pdf, err := renderPDF(testSigningContext(), doc)
	if err != nil {
		t.Fatal(err)
	}

	icc := findICCStreamInPDF(pdf)
	if icc == nil {
		t.Fatal("ICC profile stream (object 7) not found in generated PDF")
	}
	if len(icc) < 128 {
		t.Fatalf("ICC profile stream is %d bytes; a valid ICC profile requires at least 128 bytes for the header", len(icc))
	}

	sig := string(icc[36:40])
	if sig != "acsp" {
		t.Errorf("ICC profile signature at bytes 36-39 = %q, want \"acsp\"", sig)
	}

	sizeField := int(binary.BigEndian.Uint32(icc[0:4]))
	if sizeField != len(icc) {
		t.Errorf("ICC profile size field = %d, stream length = %d; they must match", sizeField, len(icc))
	}
}
