apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-crypto-provider-signer
spec:
  selector:
    app.kubernetes.io/name: crypto-provider-signer
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.signer.service.type }}
  ports:
    - name: http
      port: {{ .Values.signer.port }}
      targetPort: http
      {{- if and (eq .Values.signer.service.type "NodePort") .Values.signer.service.nodePort }}
      nodePort: {{ .Values.signer.service.nodePort }}
      {{- end }}
