apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-crypto-provider-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: vault
          image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}"
          imagePullPolicy: {{ .Values.vault.image.pullPolicy }}
          {{- if .Values.vault.dev.enabled }}
          args: ["server", "-dev", "-dev-root-token-id={{ .Values.vault.dev.rootToken }}"]
          {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.vault.service.port }}
          env:
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:{{ .Values.vault.service.port }}"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- with .Values.vault.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
