apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-crypto-provider-vault
spec:
  type: {{ .Values.vault.service.type | default "ClusterIP" }}
  ports:
    - name: api
      port: {{ .Values.vault.service.port }}
      targetPort: api
      {{- if and (eq (.Values.vault.service.type | default "ClusterIP") "NodePort") .Values.vault.service.nodePort }}
      nodePort: {{ .Values.vault.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: {{ .Release.Name }}
