apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hydra
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: public
      port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.publicNodePort }}
      nodePort: {{ .Values.service.publicNodePort }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.adminNodePort }}
      nodePort: {{ .Values.service.adminNodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: {{ .Release.Name }}
