Feature: Large document page wrapping
  Scenario: A document with many sections, ontology terms, and signatures wraps across multiple pages
    Given the compiler service is running
    And a semantic payload:
      """
      {
        "@context": {
          "@vocab": "http://127.0.0.1:8080/ontology/dcs-pdf-core#",
          "prov": "http://www.w3.org/ns/prov#",
          "odrl": "http://www.w3.org/ns/odrl/2/",
          "schema": "https://schema.org/",
          "dcs-pdf-core": "http://127.0.0.1:8080/ontology/dcs-pdf-core#",
          "xsd": "http://www.w3.org/2001/XMLSchema#"
        },
        "@id": "urn:doc:large-document",
        "@type": ["dcs-pdf-core:Document", "prov:Bundle"],
        "title": "Master Services Agreement",
        "signatureFields": [
          {"@type": "dcs-pdf-core:SignatureField", "name": "ClientSignature"},
          {"@type": "dcs-pdf-core:SignatureField", "name": "ProviderSignature"},
          {"@type": "dcs-pdf-core:SignatureField", "name": "WitnessSignature"}
        ],
        "sections": [
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "1. Scope and Purpose",
            "clauses": [
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "This agreement governs all services delivered as a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Activity"},
                  " by the provider, constituting a formal ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "odrl:Policy"},
                  " binding on all parties."
                ]
              },
              "The scope of this document extends to all subsidiaries, affiliates, and third-party contractors operating under the authority of the principal party as defined in section two.",
              "Nothing in this section shall be construed to limit the rights granted under applicable law or any superseding regulatory framework in the relevant jurisdiction."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "2. Definitions",
            "clauses": [
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "Service means the deterministic document compilation platform. Each compiled document is a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Entity"},
                  " whose provenance is fully captured in the embedded JSON-LD graph."
                ]
              },
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "Payload means any structured JSON-LD graph submitted to the compilation endpoint. The canonical form of the payload is the authoritative source for the ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:wasDerivedFrom"},
                  " relationship recorded in the manifest."
                ]
              },
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "Artifact means any PDF produced by the service. The artifact is a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Entity"},
                  " generated by a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Activity"},
                  " associated with a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:SoftwareAgent"},
                  " acting as the compiler runtime."
                ]
              }
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "3. Obligations of the Provider",
            "clauses": [
              "The provider shall maintain the compilation service in an operational state for no less than ninety-nine point nine percent of each calendar month, measured across all documented API endpoints.",
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "The provider shall ensure that each compiled artifact faithfully represents the semantic content of the original ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Entity"},
                  " graph, with all ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "odrl:Permission"},
                  " grants recorded accurately."
                ]
              },
              "The provider shall not retain submitted payload data beyond the duration required to produce the compiled artifact, except where retention is required by applicable law."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "4. Obligations of the Client",
            "clauses": [
              "The client shall ensure that all submitted payloads comply with the JSON-LD 1.1 specification and the ontology constraints published at the service ontology endpoint.",
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "The client acknowledges that each submission constitutes a ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Activity"},
                  " and accepts responsibility for the accuracy of all asserted ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:wasDerivedFrom"},
                  " relationships."
                ]
              },
              "The client shall retain copies of all compiled artifacts and bears sole responsibility for their subsequent storage, distribution, and legal validity."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "5. Intellectual Property",
            "clauses": [
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "All intellectual property rights in the compilation service remain vested in the provider. Full specification is available at ",
                  "https://schema.org/softwareVersion",
                  "."
                ]
              },
              "The client retains all intellectual property rights in the payload content submitted to the service and in the compiled artifacts produced therefrom.",
              "No licence is granted to either party to use the other party's trademarks, trade names, or registered marks without prior written consent."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "6. Limitation of Liability",
            "clauses": [
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "In no event shall the provider be liable for any indirect or consequential damages. The permitted remedies are constrained by the ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "odrl:Constraint"},
                  " declared in the applicable ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "odrl:Policy"},
                  "."
                ]
              },
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "The provider's total cumulative liability shall not exceed the total fees paid by the client in the twelve months preceding the claim, expressed as the ",
                  "100",
                  " GBP cap unless otherwise agreed in writing."
                ]
              },
              "Nothing in this section shall exclude liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "7. Governing Law",
            "clauses": [
              "This agreement shall be governed by and construed in accordance with the laws of the applicable jurisdiction without regard to its conflict of law provisions.",
              "Any dispute arising under or in connection with this agreement shall be subject to the exclusive jurisdiction of the courts of the designated forum.",
              "The parties agree to attempt in good faith to resolve any dispute through mediation before initiating formal legal proceedings."
            ]
          },
          {
            "@type": "dcs-pdf-core:Section",
            "heading": "8. Amendments and Severability",
            "clauses": [
              {
                "@type": "dcs-pdf-core:Clause",
                "content": [
                  "Any amendment must be made in writing. Incremental updates applied through the ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Activity"},
                  " mechanism of the compilation service constitute valid written amendments, each producing a new ",
                  {"@type": "dcs-pdf-core:ContentNode", "@id": "prov:Entity"},
                  " in the provenance chain."
                ]
              },
              "If any provision of this agreement is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.",
              "The invalidity of a provision in one jurisdiction shall not affect the validity of that provision in any other jurisdiction."
            ]
          }
        ]
      }
      """
    When I compile the payload through /download
    Then the response content type is "application/pdf"
    And the compiled PDF spans at least 2 pages
    And the PDF contains these markers:
      | marker              |
      | /AcroForm           |
      | /FT /Sig            |
      | /T (ClientSignature)    |
      | /T (ProviderSignature)  |
      | /T (WitnessSignature)   |
      | /Outlines           |
      | (prov:Entity) Tj    |
      | (odrl:Policy) Tj    |
      | /XYZ 54.00          |
