apiVersion: v2
name: digital-contracting-service
description: A Helm chart for Kubernetes

type: application
version: 0.2.2
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "0.1.0"
    repository: "file://charts/postgresql"
    condition: postgresql.enabled
  - name: hydra
    version: "0.1.0"
    repository: "file://charts/hydra"
    condition: hydra.enabled
  - name: nats
    version: "0.1.0"
    repository: "file://charts/nats"
    condition: nats.enabled
  - name: orce
    version: "0.1.0"
    repository: "file://charts/orce"
    condition: orce.enabled
  - name: dss
    version: "0.1.0"
    repository: "file://charts/dss"
    condition: dss.enabled
  - name: fc-service
    version: "0.4.0"
    repository: "oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/catalogue"
    condition: fcservice.enabled
    alias: fcservice
  - name: ipfs
    version: "0.1.0"
    repository: "file://charts/ipfs"
    condition: ipfs.enabled
    alias: ipfs
  - name: ipfs-document-manager
    version: "0.1.0"
    repository: "file://charts/ipfs-document-manager"
    condition: ipfsDocumentManager.enabled
    alias: ipfsDocumentManager
  - name: statuslist-service
    version: "0.1.0"
    repository: "file://charts/statuslist-service"
    condition: statuslistService.enabled
    alias: statuslistService
  - name: kube-prometheus-stack
    version: "85.2.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
  - name: traefik
    version: "41.0.0"
    repository: "https://traefik.github.io/charts"
    condition: traefik.enabled
