apiVersion: v2
name: digital-contracting-service
description: A Helm chart for Kubernetes

type: application
version: 0.2.2
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "0.1.0"
    repository: "file://charts/postgresql"
    condition: postgresql.enabled
  - name: keycloak
    version: "0.1.0"
    repository: "file://charts/keycloak"
    condition: keycloak.enabled
  - name: nats
    version: "0.1.0"
    repository: "file://charts/nats"
    condition: nats.enabled
  - name: neo4j
    version: "0.1.0"
    repository: "file://charts/neo4j"
    condition: neo4j.enabled
  - name: federated-catalogue
    version: "0.1.0"
    repository: "file://charts/federated-catalogue"
    condition: federatedCatalogue.enabled
    alias: federatedCatalogue
  - name: custom-policy-agent
    version: "0.1.0"
    repository: "file://charts/custom-policy-agent"
    condition: customPolicyAgent.enabled
    alias: customPolicyAgent
  - name: mongodb
    version: "0.1.0"
    repository: "file://charts/mongodb"
    condition: mongodb.enabled
    alias: mongodb
  - name: ipfs
    version: "0.1.0"
    repository: "file://charts/ipfs"
    condition: ipfs.enabled
    alias: ipfs
  - name: ipfs-document-manager
    version: "0.1.0"
    repository: "file://charts/ipfs-document-manager"
    condition: ipfsDocumentManager.enabled
    alias: ipfsDocumentManager
