name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    # TODO: must be eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    # See PR: https://github.com/eclipse-xfsc/dev-ops/pull/9
    uses: arnemileswinter/xfsc-dev-ops/.github/workflows/dockerbuild.yml@main
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_CREDENTIALS: ${{ secrets.HARBOR_CREDENTIALS }}
    with: 
      dockerfile: "deployment/docker/Dockerfile"
      harbor_config: "deployment/harbor.config"
  dockerbuild-pdf-core:
    # TODO: must be eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    # See PR: https://github.com/eclipse-xfsc/dev-ops/pull/9
    uses: arnemileswinter/xfsc-dev-ops/.github/workflows/dockerbuild.yml@main
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_CREDENTIALS: ${{ secrets.HARBOR_CREDENTIALS }}
    with:
      dockerfile: "pdf-core/Dockerfile"
      buildContext: "."
      service: "pdf-core"
      harbor_config: "deployment/harbor.config"