name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@harbor-env-patch
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_CREDENTIALS: ${{ secrets.HARBOR_CREDENTIALS }}
    with: 
      dockerfile: "deployment/docker/Dockerfile"
      harbor_config: "deployment/harbor.config"
  dockerbuild-pdf-core:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@harbor-env-patch
    secrets:
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_CREDENTIALS: ${{ secrets.HARBOR_CREDENTIALS }}
    with:
      dockerfile: "pdf-core/Dockerfile"
      buildContext: "."
      service: "pdf-core"
      harbor_config: "deployment/harbor.config"